/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cancerdetection;

import cancerdetection.jdbcconnection.JDBCTemplate;
import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import resultgeneration.result;

/**
 *
 * @author RAHUL
 */
public class PrecautionsSCLC extends javax.swing.JFrame {

    /**
     * Creates new form Precautions
     */
    String id,name;
    public PrecautionsSCLC(String ID) {
        initComponents();
        id=new String(ID);
        System.out.println("precautionssclc user = "+id);
        
        try
		    {
		     java.sql.Connection c=null;
		     c=JDBCTemplate.getConnection();
		     java.sql.Statement str=c.createStatement();
                     
		     str.execute("update user set win_status=14 where email='"+id+"'");
		     System.out.println("update win status with 14 by precautionsSCLC");
                     
                     java.sql.ResultSet rs3=str.executeQuery("SELECT name  FROM user WHERE email='"+id+"'");
		    if(rs3.next())
		    {
                        System.out.println(rs3.getString(1));
                        name=rs3.getString(1);
                        jLabel13.setText(name);
                    }
                    
		    }
		    catch(Exception e)
		    {
                         System.out.println(e);  
		    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1375, 1678));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1375, 1678));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText(".....Precautions you have to take when you are suffering from Lung Cancer and also to avoid lung cancer.....");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("1.Try to limit your sun exposure between 10:00 am and 3:00 pm, which is when the sun's rays are strongest.");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("2.Use sunscreen with an SPF of 30 or higher and reapply it often, especially after sweating");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("3.Dress for sun protection, and bring portable shade such as an umbrella if possible.");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("4.Protect your head. If you've lost your hair due to chemo, wear a hat.");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("5.If you have undergone radiation, know the boundaries of where you were exposed.");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("6.Keep any surgical scars covered from the sun.");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("7.Hydrate Keep fluids on-hand. Eat small, frequent meals.");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("8.Listen to your body. Rest if you feel tired.");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("9.Exercise can help combat fatigue, but recognize your limits.");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("<-Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Exit->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Final Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(650, 650, 650))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(1190, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Enhancing Performance of Medical Expert System by Crisp Logic");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248)
                .addComponent(jLabel13)
                .addGap(89, 89, 89))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1499, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1683, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new TreatmentsSCLC(id).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainFrame(id).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            
            int t=0,q=0;
            
            java.sql.Connection c=null;
		     c=JDBCTemplate.getConnection();
		     java.sql.Statement str=c.createStatement();
                     
                     java.sql.ResultSet rs3=str.executeQuery("SELECT *  FROM result WHERE email='"+id+"'");
		     if(rs3.next())
		      {
                          if(rs3.getString(1).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(1));
                          }
                           
                          if(rs3.getString(2).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(2));
                          }
                          
                          if(rs3.getString(3).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(3));
                          }
                          
                          if(rs3.getString(4).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(4));
                          }
                          
                          if(rs3.getString(5).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(5));
                          }
                          
                          if(rs3.getString(6).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(6));
                          }
                          
                          if(rs3.getString(7).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(7));
                          }
                          
                          if(rs3.getString(8).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(8));
                          }
                          
                          if(rs3.getString(9).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(9));
                          }
                          
                          if(rs3.getString(10).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(10));
                          }
                          
                          if(rs3.getString(11).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(11));
                          }
                          
                          if(rs3.getString(12).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(12));
                          }
                          
                          if(rs3.getString(13).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(13));
                          }
                          
                          if(rs3.getString(14).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(14));
                          }
                          
                          if(rs3.getString(15).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(15));
                          }
                          
                          if(rs3.getString(16).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(16));
                          }
                          
                          if(rs3.getString(17).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(17));
                          }
                          
                          if(rs3.getString(18).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(18));
                          }
                          
                          if(rs3.getString(19).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(19));
                          }
                          
                          if(rs3.getString(20).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(20));
                          }
                          
                          if(rs3.getString(21).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(21));
                          }
                          
                          if(rs3.getString(22).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(22));
                          }
                          
                          if(rs3.getString(23).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(23));
                          }
                          
                          if(rs3.getString(24).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(24));
                          }
                          
                          if(rs3.getString(25).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(25));
                          }
                          
                          if(rs3.getString(26).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(26));
                          }
                          
                          if(rs3.getString(27).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(27));
                          }
                          
                          if(rs3.getString(28).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(28));
                          }
                          
                          if(rs3.getString(29).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(29));
                          }
                          
                          if(rs3.getString(30).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(30));
                          }
                          
                          if(rs3.getString(31).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(31));
                          }
                          
                          if(rs3.getString(32).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(32));
                          }
                          
                          if(rs3.getString(33).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(33));
                          }
                          
                          if(rs3.getString(34).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(34));
                          }
                          
                          if(rs3.getString(35).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(35));
                          }
                          
                          if(rs3.getString(36).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(36));
                          }
                          
                          if(rs3.getString(37).equals("YES"))
                          {
                              q++;
                              System.out.println(rs3.getString(37));
                          }
                          
                         System.out.println("question yes = "+q);
                         
                          if(rs3.getString(38).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(38));
                          }
                          
                          if(rs3.getString(39).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(39));
                          }
                          
                          if(rs3.getString(40).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(40));
                          }
                          
                   
                          if(rs3.getString(41).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(41));
                          }
                          if(rs3.getString(42).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(42));
                          }
                          if(rs3.getString(43).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(43));
                          }
                          if(rs3.getString(44).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(44));
                          }
                          if(rs3.getString(45).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(45));
                          }
                          if(rs3.getString(46).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(46));
                          }
                          if(rs3.getString(47).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(47));
                          }
                          if(rs3.getString(48).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(48));
                          }
                           if(rs3.getString(49).equals("POSITIVE"))
                          {
                              t++;
                              System.out.println(rs3.getString(49));
                          }
                           
                           System.out.println("Test pos = "+t);
                         
                       }
                     
                     
                     
                     System.out.println("\nQue = "+q+"\ntest = "+t);
                     if(q>=22&&t>=9)
                     {
                          System.out.println("positive result generated..");
                          new result(id);
                          dispose();
                          new MainFrame(id).setVisible(true);
                     }
                     else{ 
                         dispose();
                         new NegativeResult(id).setVisible(true);
                         
                     }
                     
                     
                     
            
        } catch (IOException ex) {
            Logger.getLogger(PrecautionsSCLC.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(PrecautionsSCLC.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PrecautionsSCLC.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
        new MainFrame(id).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrecautionsSCLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrecautionsSCLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrecautionsSCLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrecautionsSCLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PrecautionsSCLC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
